"""
Caddy Configuration Manager for AppZ Hosting

Generates and manages Caddyfile for reverse proxy.
"""

import frappe


def generate_caddyfile(server_name):
    """Generate Caddyfile from all running services on server"""
    services = frappe.get_all(
        "Hosted Service",
        filters={
            "server": server_name,
            "status": "Active"
        },
        fields=["name", "domain", "plan"]
    )

    caddyfile = """# Auto-generated by AppZ Hosting
# Do not edit manually - changes will be overwritten

{
    email ssl@appz.studio
    acme_ca https://acme-v02.api.letsencrypt.org/directory
}

"""

    for service in services:
        plan = frappe.get_doc("Service Plan", service.plan)
        template = frappe.get_doc("Deployment Template", plan.template)
        port = template.internal_port or 80
        container = f"{service.name}-app"

        caddyfile += f"""
# Service: {service.name}
{service.domain} {{
    reverse_proxy {container}:{port}
    encode gzip

    header {{
        X-Content-Type-Options nosniff
        X-Frame-Options SAMEORIGIN
        Referrer-Policy strict-origin-when-cross-origin
        -Server
    }}

    log {{
        output file /var/log/caddy/{service.domain}.log {{
            roll_size 10mb
            roll_keep 5
        }}
    }}
}}

"""

    return caddyfile


def add_service_to_caddy(server_name, service_name):
    """Add a single service to Caddyfile"""
    from appz_hosting.core.deployer import Deployer

    caddyfile = generate_caddyfile(server_name)

    deployer = Deployer(server_name)
    deployer._upload_file(caddyfile, "/apps/caddy/Caddyfile")
    deployer._exec("docker exec caddy caddy reload --config /etc/caddy/Caddyfile")


def remove_service_from_caddy(server_name, service_name):
    """Remove a service from Caddyfile"""
    # Just regenerate without the service
    add_service_to_caddy(server_name, service_name)
